name: pages-update

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          set -x

          curl \
            --fail \
            --show-error \
            --location \
            --output releases_latest.json \
            --header "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest

          export HUGO_VRM_ADDON_FOR_BLENDER_LATEST_VERSION_NAME=$(ruby -rjson -e "puts JSON.parse(File.read('releases_latest.json'))['name']")
          export HUGO_VRM_ADDON_FOR_BLENDER_LATEST_PUBLISH_DATE=$(ruby -rjson -e "puts JSON.parse(File.read('releases_latest.json'))['published_at']")

          hugo_dir=$(mktemp -d)

          pushd "$hugo_dir"
          wget -q https://github.com/gohugoio/hugo/releases/download/v0.91.2/hugo_extended_0.91.2_Linux-64bit.tar.gz
          tar xf hugo_extended_0.91.2_Linux-64bit.tar.gz
          popd

          git fetch --depth=1 origin gh-pages
          cd docs/website
          mkdir public
          pushd public
            ln -s ../../../.git .git
            git checkout gh-pages
          popd

          "$hugo_dir/hugo" --minify

      - name: Deploy
        run: |
          set -x

          case "$(git rev-parse HEAD)" in
            "$(git rev-parse origin/main)");;
            "$(git rev-parse origin/website)");;
            *) exit 0;;
          esac

          cd docs/website/public
          git add .
          if git diff --cached --exit-code; then
            exit 0
          fi
          git config --global user.email "isamu@leafytree.jp"
          git config --global user.name "Isamu Mogi (BOT)"
          git commit -m "(BOT) Update"
          git push origin gh-pages
