name: release

on:
  push:
    tags:
      - '*_*_*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install package
        run: |
          sudo apt-get update -qq || true
          sudo apt-get install -y advancecomp curl git python3 ruby shellcheck blender
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Release
        run: ./scripts/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
