name: Test

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [master]

jobs:
  test-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Install Blender
        run: choco install blender --yes --no-progress --version 2.82.1
      - name: Test
        run: |
          &"C:\Program Files\Blender Foundation\Blender 2.82\2.82\python\bin\python.exe" `
            test\run.py `
            "C:\Program Files\Blender Foundation\Blender 2.82\blender.exe"

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Blender
        run: brew cask install blender
      - name: Test
        run: ./test/run.py

  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install deb packages
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y nkf python3-pip
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Check character encoding
        run: |
          find . -name '*.py' -exec nkf -w -Lu -Z1 --in-place {} +
          find . -name '*.md' -exec nkf -w -Lu -Z1 --in-place {} +
          git diff --exit-code
      - name: Install pip packages
        run: |
          pip3 install --upgrade pip
          pip3 install flake8 pep8-naming
          echo "::add-path::$HOME/.local/bin"
      - name: Lint
        run: flake8 . --count --show-source --statistics
