name: Test

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        blender-version: [2.82]

    steps:
    - uses: actions/checkout@v2
    - name: Install blender
      run: |
        # TODO: Freeze version
        sudo apt-get update -qq
        sudo apt-get install blender python3-numpy python3-pip
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install black flake8
        echo "::add-path::$HOME/.local/bin"
    - name: Lint with black
      run: |
        black --check $(find . -type d)
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test
      run: |
        ./test/run.py
